/*! jQuery UI v1.10.3 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
*/
(function(b,p){function f(a,k){var e,c;e=a.nodeName.toLowerCase();if("area"===e){e=a.parentNode;c=e.name;if(!a.href||!c||"map"!==e.nodeName.toLowerCase())return!1;e=b("img[usemap=#"+c+"]")[0];return!!e&&g(e)}return(/input|select|textarea|button|object/.test(e)?!a.disabled:"a"===e?a.href||k:k)&&g(a)}function g(a){return b.expr.filters.visible(a)&&!b(a).parents().addBack().filter(function(){return"hidden"===b.css(this,"visibility")}).length}var c=0,a=/^ui-id-\d+$/;b.ui=b.ui||{};b.extend(b.ui,{version:"1.10.3",
keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38}});b.fn.extend({focus:function(a){return function(k,e){return"number"===typeof k?this.each(function(){var a=this;setTimeout(function(){b(a).focus();e&&e.call(a)},k)}):a.apply(this,arguments)}}(b.fn.focus),scrollParent:function(){var a;a=
b.ui.ie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0);return/fixed/.test(this.css("position"))||!a.length?b(document):
a},zIndex:function(a){if(a!==p)return this.css("zIndex",a);if(this.length){a=b(this[0]);for(var k;a.length&&a[0]!==document;){k=a.css("position");if("absolute"===k||"relative"===k||"fixed"===k)if(k=parseInt(a.css("zIndex"),10),!isNaN(k)&&0!==k)return k;a=a.parent()}}return 0},uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++c)})},removeUniqueId:function(){return this.each(function(){a.test(this.id)&&b(this).removeAttr("id")})}});b.extend(b.expr[":"],{data:b.expr.createPseudo?
b.expr.createPseudo(function(a){return function(k){return!!b.data(k,a)}}):function(a,k,e){return!!b.data(a,e[3])},focusable:function(a){return f(a,!isNaN(b.attr(a,"tabindex")))},tabbable:function(a){var k=b.attr(a,"tabindex"),e=isNaN(k);return(e||0<=k)&&f(a,!e)}});b("<a>").outerWidth(1).jquery||b.each(["Width","Height"],function(a,k){function e(a,d,k,e){b.each(c,function(){d-=parseFloat(b.css(a,"padding"+this))||0;k&&(d-=parseFloat(b.css(a,"border"+this+"Width"))||0);e&&(d-=parseFloat(b.css(a,"margin"+
this))||0)});return d}var c="Width"===k?["Left","Right"]:["Top","Bottom"],h=k.toLowerCase(),f={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+k]=function(a){return a===p?f["inner"+k].call(this):this.each(function(){b(this).css(h,e(this,a)+"px")})};b.fn["outer"+k]=function(a,d){return"number"!==typeof a?f["outer"+k].call(this,a):this.each(function(){b(this).css(h,e(this,a,!0,d)+"px")})}});b.fn.addBack||(b.fn.addBack=function(a){return this.add(null==
a?this.prevObject:this.prevObject.filter(a))});b("<a>").data("a-b","a").removeData("a-b").data("a-b")&&(b.fn.removeData=function(a){return function(k){return arguments.length?a.call(this,b.camelCase(k)):a.call(this)}}(b.fn.removeData));b.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());b.support.selectstart="onselectstart"in document.createElement("div");b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",
function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.extend(b.ui,{plugin:{add:function(a,k,e){var c;a=b.ui[a].prototype;for(c in e)a.plugins[c]=a.plugins[c]||[],a.plugins[c].push([k,e[c]])},call:function(a,b,e){var c=a.plugins[b];if(c&&a.element[0].parentNode&&11!==a.element[0].parentNode.nodeType)for(b=0;b<c.length;b++)a.options[c[b][0]]&&c[b][1].apply(a.element,e)}},hasScroll:function(a,k){if("hidden"===b(a).css("overflow"))return!1;var e=
k&&"left"===k?"scrollLeft":"scrollTop",c=!1;if(0<a[e])return!0;a[e]=1;c=0<a[e];a[e]=0;return c}})})(jQuery);
(function(b,p){var f=0,g=Array.prototype.slice,c=b.cleanData;b.cleanData=function(a){for(var d=0,k;null!=(k=a[d]);d++)try{b(k).triggerHandler("remove")}catch(e){}c(a)};b.widget=function(a,d,k){var e,c,h,f,g={},n=a.split(".")[0];a=a.split(".")[1];e=n+"-"+a;k||(k=d,d=b.Widget);b.expr[":"][e.toLowerCase()]=function(a){return!!b.data(a,e)};b[n]=b[n]||{};c=b[n][a];h=b[n][a]=function(a,b){if(!this._createWidget)return new h(a,b);arguments.length&&this._createWidget(a,b)};b.extend(h,c,{version:k.version,
_proto:b.extend({},k),_childConstructors:[]});f=new d;f.options=b.widget.extend({},f.options);b.each(k,function(a,e){b.isFunction(e)?g[a]=function(){var b=function(){return d.prototype[a].apply(this,arguments)},k=function(b){return d.prototype[a].apply(this,b)};return function(){var a=this._super,d=this._superApply,c;this._super=b;this._superApply=k;c=e.apply(this,arguments);this._super=a;this._superApply=d;return c}}():g[a]=e});h.prototype=b.widget.extend(f,{widgetEventPrefix:c?f.widgetEventPrefix:
a},g,{constructor:h,namespace:n,widgetName:a,widgetFullName:e});c?(b.each(c._childConstructors,function(a,d){var e=d.prototype;b.widget(e.namespace+"."+e.widgetName,h,d._proto)}),delete c._childConstructors):d._childConstructors.push(h);b.widget.bridge(a,h)};b.widget.extend=function(a){for(var d=g.call(arguments,1),k=0,e=d.length,c,h;k<e;k++)for(c in d[k])h=d[k][c],d[k].hasOwnProperty(c)&&h!==p&&(b.isPlainObject(h)?a[c]=b.isPlainObject(a[c])?b.widget.extend({},a[c],h):b.widget.extend({},h):a[c]=h);
return a};b.widget.bridge=function(a,d){var k=d.prototype.widgetFullName||a;b.fn[a]=function(e){var c="string"===typeof e,h=g.call(arguments,1),f=this;e=!c&&h.length?b.widget.extend.apply(null,[e].concat(h)):e;c?this.each(function(){var d,c=b.data(this,k);if(!c)return b.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+e+"'");if(!b.isFunction(c[e])||"_"===e.charAt(0))return b.error("no such method '"+e+"' for "+a+" widget instance");d=c[e].apply(c,h);if(d!==
c&&d!==p)return f=d&&d.jquery?f.pushStack(d.get()):d,!1}):this.each(function(){var a=b.data(this,k);a?a.option(e||{})._init():b.data(this,k,new d(e,this))});return f}};b.Widget=function(){};b.Widget._childConstructors=[];b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{disabled:!1,create:null},_createWidget:function(a,d){d=b(d||this.defaultElement||this)[0];this.element=b(d);this.uuid=f++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=b.widget.extend({},
this.options,this._getCreateOptions(),a);this.bindings=b();this.hoverable=b();this.focusable=b();d!==this&&(b.data(d,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===d&&this.destroy()}}),this.document=b(d.style?d.ownerDocument:d.document||d),this.window=b(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:b.noop,_getCreateEventData:b.noop,_create:b.noop,
_init:b.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(b.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:b.noop,widget:function(){return this.element},
option:function(a,d){var c=a,e,f,h;if(0===arguments.length)return b.widget.extend({},this.options);if("string"===typeof a)if(c={},e=a.split("."),a=e.shift(),e.length){f=c[a]=b.widget.extend({},this.options[a]);for(h=0;h<e.length-1;h++)f[e[h]]=f[e[h]]||{},f=f[e[h]];a=e.pop();if(d===p)return f[a]===p?null:f[a];f[a]=d}else{if(d===p)return this.options[a]===p?null:this.options[a];c[a]=d}this._setOptions(c);return this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,
b){this.options[a]=b;"disabled"===a&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!b).attr("aria-disabled",b),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(a,d,c){var e,f=this;"boolean"!==typeof a&&(c=d,d=a,a=!1);c?(d=e=b(d),this.bindings=this.bindings.add(d)):(c=d,d=this.element,e=
this.widget());b.each(c,function(c,k){function g(){if(a||!0!==f.options.disabled&&!b(this).hasClass("ui-state-disabled"))return("string"===typeof k?f[k]:k).apply(f,arguments)}"string"!==typeof k&&(g.guid=k.guid=k.guid||g.guid||b.guid++);var n=c.match(/^(\w+)\s*(.*)$/),r=n[1]+f.eventNamespace;(n=n[2])?e.delegate(n,r,g):d.bind(r,g)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;a.unbind(b).undelegate(b)},_delay:function(a,b){var c=this;return setTimeout(function(){return("string"===
typeof a?c[a]:a).apply(c,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){b(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){b(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){b(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){b(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(a,d,c){var e,
f=this.options[a];c=c||{};d=b.Event(d);d.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();d.target=this.element[0];if(a=d.originalEvent)for(e in a)e in d||(d[e]=a[e]);this.element.trigger(d,c);return!(b.isFunction(f)&&!1===f.apply(this.element[0],[d].concat(c))||d.isDefaultPrevented())}};b.each({show:"fadeIn",hide:"fadeOut"},function(a,d){b.Widget.prototype["_"+a]=function(c,e,f){"string"===typeof e&&(e={effect:e});var h,g=e?!0===e||"number"===typeof e?d:e.effect||d:a;e=
e||{};"number"===typeof e&&(e={duration:e});h=!b.isEmptyObject(e);e.complete=f;e.delay&&c.delay(e.delay);if(h&&b.effects&&b.effects.effect[g])c[a](e);else if(g!==a&&c[g])c[g](e.duration,e.easing,f);else c.queue(function(d){b(this)[a]();f&&f.call(c[0]);d()})}})})(jQuery);
(function(b,p){var f=!1;b(document).mouseup(function(){f=!1});b.widget("ui.mouse",{version:"1.10.3",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0},_mouseInit:function(){var f=this;this.element.bind("mousedown."+this.widgetName,function(b){return f._mouseDown(b)}).bind("click."+this.widgetName,function(c){if(!0===b.data(c.target,f.widgetName+".preventClickEvent"))return b.removeData(c.target,f.widgetName+".preventClickEvent"),c.stopImmediatePropagation(),!1});this.started=
!1},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);this._mouseMoveDelegate&&b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(g){if(!f){this._mouseStarted&&this._mouseUp(g);this._mouseDownEvent=g;var c=this,a=1===g.which,d="string"===typeof this.options.cancel&&g.target.nodeName?b(g.target).closest(this.options.cancel).length:!1;if(!a||d||!this._mouseCapture(g))return!0;this.mouseDelayMet=
!this.options.delay;this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){c.mouseDelayMet=!0},this.options.delay));if(this._mouseDistanceMet(g)&&this._mouseDelayMet(g)&&(this._mouseStarted=!1!==this._mouseStart(g),!this._mouseStarted))return g.preventDefault(),!0;!0===b.data(g.target,this.widgetName+".preventClickEvent")&&b.removeData(g.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(a){return c._mouseMove(a)};this._mouseUpDelegate=function(a){return c._mouseUp(a)};
b(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);g.preventDefault();return f=!0}},_mouseMove:function(f){if(b.ui.ie&&(!document.documentMode||9>document.documentMode)&&!f.button)return this._mouseUp(f);if(this._mouseStarted)return this._mouseDrag(f),f.preventDefault();this._mouseDistanceMet(f)&&this._mouseDelayMet(f)&&((this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,f))?this._mouseDrag(f):this._mouseUp(f));
return!this._mouseStarted},_mouseUp:function(f){b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,f.target===this._mouseDownEvent.target&&b.data(f.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(f));return!1},_mouseDistanceMet:function(b){return Math.max(Math.abs(this._mouseDownEvent.pageX-b.pageX),Math.abs(this._mouseDownEvent.pageY-b.pageY))>=this.options.distance},
_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}})})(jQuery);
(function(b,p){function f(a,b,d){return[parseFloat(a[0])*(s.test(a[0])?b/100:1),parseFloat(a[1])*(s.test(a[1])?d/100:1)]}function g(a){var d=a[0];return 9===d.nodeType?{width:a.width(),height:a.height(),offset:{top:0,left:0}}:b.isWindow(d)?{width:a.width(),height:a.height(),offset:{top:a.scrollTop(),left:a.scrollLeft()}}:d.preventDefault?{width:0,height:0,offset:{top:d.pageY,left:d.pageX}}:{width:a.outerWidth(),height:a.outerHeight(),offset:a.offset()}}b.ui=b.ui||{};var c,a=Math.max,d=Math.abs,k=
Math.round,e=/left|center|right/,l=/top|center|bottom/,h=/[\+\-]\d+(\.[\d]+)?%?/,m=/^\w+/,s=/%$/,n=b.fn.position;b.position={scrollbarWidth:function(){if(c!==p)return c;var a,d,e=b("<div style='display:block;width:50px;height:50px;overflow:hidden;'><div style='height:100px;width:auto;'></div></div>");d=e.children()[0];b("body").append(e);a=d.offsetWidth;e.css("overflow","scroll");d=d.offsetWidth;a===d&&(d=e[0].clientWidth);e.remove();return c=a-d},getScrollInfo:function(a){var d=a.isWindow?"":a.element.css("overflow-x"),
c=a.isWindow?"":a.element.css("overflow-y"),d="scroll"===d||"auto"===d&&a.width<a.element[0].scrollWidth;return{width:"scroll"===c||"auto"===c&&a.height<a.element[0].scrollHeight?b.position.scrollbarWidth():0,height:d?b.position.scrollbarWidth():0}},getWithinInfo:function(a){a=b(a||window);var d=b.isWindow(a[0]);return{element:a,isWindow:d,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),width:d?a.width():a.outerWidth(),height:d?a.height():a.outerHeight()}}};b.fn.position=
function(c){if(!c||!c.of)return n.apply(this,arguments);c=b.extend({},c);var q,y,w,x,t,v,s=b(c.of),A=b.position.getWithinInfo(c.within),E=b.position.getScrollInfo(A),z=(c.collision||"flip").split(" "),D={};v=g(s);s[0].preventDefault&&(c.at="left top");y=v.width;w=v.height;x=v.offset;t=b.extend({},x);b.each(["my","at"],function(){var a=(c[this]||"").split(" "),b,d;1===a.length&&(a=e.test(a[0])?a.concat(["center"]):l.test(a[0])?["center"].concat(a):["center","center"]);a[0]=e.test(a[0])?a[0]:"center";
a[1]=l.test(a[1])?a[1]:"center";b=h.exec(a[0]);d=h.exec(a[1]);D[this]=[b?b[0]:0,d?d[0]:0];c[this]=[m.exec(a[0])[0],m.exec(a[1])[0]]});1===z.length&&(z[1]=z[0]);"right"===c.at[0]?t.left+=y:"center"===c.at[0]&&(t.left+=y/2);"bottom"===c.at[1]?t.top+=w:"center"===c.at[1]&&(t.top+=w/2);q=f(D.at,y,w);t.left+=q[0];t.top+=q[1];return this.each(function(){var e,h,g=b(this),l=g.outerWidth(),v=g.outerHeight(),m=parseInt(b.css(this,"marginLeft"),10)||0,n=parseInt(b.css(this,"marginTop"),10)||0,p=l+m+(parseInt(b.css(this,
"marginRight"),10)||0)+E.width,F=v+n+(parseInt(b.css(this,"marginBottom"),10)||0)+E.height,u=b.extend({},t),B=f(D.my,g.outerWidth(),g.outerHeight());"right"===c.my[0]?u.left-=l:"center"===c.my[0]&&(u.left-=l/2);"bottom"===c.my[1]?u.top-=v:"center"===c.my[1]&&(u.top-=v/2);u.left+=B[0];u.top+=B[1];b.support.offsetFractions||(u.left=k(u.left),u.top=k(u.top));e={marginLeft:m,marginTop:n};b.each(["left","top"],function(a,d){if(b.ui.position[z[a]])b.ui.position[z[a]][d](u,{targetWidth:y,targetHeight:w,
elemWidth:l,elemHeight:v,collisionPosition:e,collisionWidth:p,collisionHeight:F,offset:[q[0]+B[0],q[1]+B[1]],my:c.my,at:c.at,within:A,elem:g})});c.using&&(h=function(b){var e=x.left-u.left,f=e+y-l,k=x.top-u.top,h=k+w-v,t={target:{element:s,left:x.left,top:x.top,width:y,height:w},element:{element:g,left:u.left,top:u.top,width:l,height:v},horizontal:0>f?"left":0<e?"right":"center",vertical:0>h?"top":0<k?"bottom":"middle"};y<l&&d(e+f)<y&&(t.horizontal="center");w<v&&d(k+h)<w&&(t.vertical="middle");a(d(e),
d(f))>a(d(k),d(h))?t.important="horizontal":t.important="vertical";c.using.call(this,b,t)});g.offset(b.extend(u,{using:h}))})};b.ui.position={fit:{left:function(b,d){var c=d.within,e=c.isWindow?c.scrollLeft:c.offset.left,f=c.width,k=b.left-d.collisionPosition.marginLeft,c=e-k,h=k+d.collisionWidth-f-e;d.collisionWidth>f?0<c&&0>=h?(e=b.left+c+d.collisionWidth-f-e,b.left+=c-e):b.left=0<h&&0>=c?e:c>h?e+f-d.collisionWidth:e:b.left=0<c?b.left+c:0<h?b.left-h:a(b.left-k,b.left)},top:function(b,d){var c=d.within,
e=c.isWindow?c.scrollTop:c.offset.top,f=d.within.height,k=b.top-d.collisionPosition.marginTop,c=e-k,h=k+d.collisionHeight-f-e;d.collisionHeight>f?0<c&&0>=h?(e=b.top+c+d.collisionHeight-f-e,b.top+=c-e):b.top=0<h&&0>=c?e:c>h?e+f-d.collisionHeight:e:b.top=0<c?b.top+c:0<h?b.top-h:a(b.top-k,b.top)}},flip:{left:function(a,b){var c=b.within,e=c.offset.left+c.scrollLeft,f=c.width,k=c.isWindow?c.scrollLeft:c.offset.left,h=a.left-b.collisionPosition.marginLeft,c=h-k,g=h+b.collisionWidth-f-k,h="left"===b.my[0]?
-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,l="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,m=-2*b.offset[0];if(0>c){if(e=a.left+h+l+m+b.collisionWidth-f-e,0>e||e<d(c))a.left+=h+l+m}else 0<g&&(e=a.left-b.collisionPosition.marginLeft+h+l+m-k,0<e||d(e)<g)&&(a.left+=h+l+m)},top:function(a,b){var c=b.within,e=c.offset.top+c.scrollTop,f=c.height,k=c.isWindow?c.scrollTop:c.offset.top,h=a.top-b.collisionPosition.marginTop,c=h-k,g=h+b.collisionHeight-f-k,h="top"===b.my[1]?-b.elemHeight:
"bottom"===b.my[1]?b.elemHeight:0,l="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,m=-2*b.offset[1];0>c?(e=a.top+h+l+m+b.collisionHeight-f-e,a.top+h+l+m>c&&(0>e||e<d(c))&&(a.top+=h+l+m)):0<g&&(e=a.top-b.collisionPosition.marginTop+h+l+m-k,a.top+h+l+m>g&&(0<e||d(e)<g)&&(a.top+=h+l+m))}},flipfit:{left:function(){b.ui.position.flip.left.apply(this,arguments);b.ui.position.fit.left.apply(this,arguments)},top:function(){b.ui.position.flip.top.apply(this,arguments);b.ui.position.fit.top.apply(this,
arguments)}}};(function(){var a,d,c,e,f=document.getElementsByTagName("body")[0];c=document.createElement("div");a=document.createElement(f?"div":"body");d={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};f&&b.extend(d,{position:"absolute",left:"-1000px",top:"-1000px"});for(e in d)a.style[e]=d[e];a.appendChild(c);d=f||document.documentElement;d.insertBefore(a,d.firstChild);c.style.cssText="position: absolute; left: 10.7432222px;";c=b(c).offset().left;b.support.offsetFractions=
10<c&&11>c;a.innerHTML="";d.removeChild(a)})()})(jQuery);
(function(b,p){var f=0,g={},c={};g.height=g.paddingTop=g.paddingBottom=g.borderTopWidth=g.borderBottomWidth="hide";c.height=c.paddingTop=c.paddingBottom=c.borderTopWidth=c.borderBottomWidth="show";b.widget("ui.accordion",{version:"1.10.3",options:{active:0,animate:{},collapsible:!1,event:"click",header:"> li > :first-child,> :not(li):even",heightStyle:"auto",icons:{activeHeader:"ui-icon-triangle-1-s",header:"ui-icon-triangle-1-e"},activate:null,beforeActivate:null},_create:function(){var a=this.options;
this.prevShow=this.prevHide=b();this.element.addClass("ui-accordion ui-widget ui-helper-reset").attr("role","tablist");a.collapsible||!1!==a.active&&null!=a.active||(a.active=0);this._processPanels();0>a.active&&(a.active+=this.headers.length);this._refresh()},_getCreateEventData:function(){return{header:this.active,panel:this.active.length?this.active.next():b(),content:this.active.length?this.active.next():b()}},_createIcons:function(){var a=this.options.icons;a&&(b("<span>").addClass("ui-accordion-header-icon ui-icon "+
a.header).prependTo(this.headers),this.active.children(".ui-accordion-header-icon").removeClass(a.header).addClass(a.activeHeader),this.headers.addClass("ui-accordion-icons"))},_destroyIcons:function(){this.headers.removeClass("ui-accordion-icons").children(".ui-accordion-header-icon").remove()},_destroy:function(){var a;this.element.removeClass("ui-accordion ui-widget ui-helper-reset").removeAttr("role");this.headers.removeClass("ui-accordion-header ui-accordion-header-active ui-helper-reset ui-state-default ui-corner-all ui-state-active ui-state-disabled ui-corner-top").removeAttr("role").removeAttr("aria-selected").removeAttr("aria-controls").removeAttr("tabIndex").each(function(){/^ui-accordion/.test(this.id)&&
this.removeAttribute("id")});this._destroyIcons();a=this.headers.next().css("display","").removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-labelledby").removeClass("ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content ui-accordion-content-active ui-state-disabled").each(function(){/^ui-accordion/.test(this.id)&&this.removeAttribute("id")});"content"!==this.options.heightStyle&&a.css("height","")},_setOption:function(a,b){"active"===a?this._activate(b):
("event"===a&&(this.options.event&&this._off(this.headers,this.options.event),this._setupEvents(b)),this._super(a,b),"collapsible"!==a||(b||!1!==this.options.active)||this._activate(0),"icons"===a&&(this._destroyIcons(),b&&this._createIcons()),"disabled"===a&&this.headers.add(this.headers.next()).toggleClass("ui-state-disabled",!!b))},_keydown:function(a){if(!a.altKey&&!a.ctrlKey){var d=b.ui.keyCode,c=this.headers.length,e=this.headers.index(a.target),f=!1;switch(a.keyCode){case d.RIGHT:case d.DOWN:f=
this.headers[(e+1)%c];break;case d.LEFT:case d.UP:f=this.headers[(e-1+c)%c];break;case d.SPACE:case d.ENTER:this._eventHandler(a);break;case d.HOME:f=this.headers[0];break;case d.END:f=this.headers[c-1]}f&&(b(a.target).attr("tabIndex",-1),b(f).attr("tabIndex",0),f.focus(),a.preventDefault())}},_panelKeyDown:function(a){a.keyCode===b.ui.keyCode.UP&&a.ctrlKey&&b(a.currentTarget).prev().focus()},refresh:function(){var a=this.options;this._processPanels();!1===a.active&&!0===a.collapsible||!this.headers.length?
(a.active=!1,this.active=b()):!1===a.active?this._activate(0):this.active.length&&!b.contains(this.element[0],this.active[0])?this.headers.length===this.headers.find(".ui-state-disabled").length?(a.active=!1,this.active=b()):this._activate(Math.max(0,a.active-1)):a.active=this.headers.index(this.active);this._destroyIcons();this._refresh()},_processPanels:function(){this.headers=this.element.find(this.options.header).addClass("ui-accordion-header ui-helper-reset");this.headers.next().addClass("ui-accordion-content ui-helper-reset").filter(":not(.ui-accordion-content-active)").hide()},
_refresh:function(){var a,d=this.options,c=d.heightStyle,e=this.element.parent(),g=this.accordionId="ui-accordion-"+(this.element.attr("id")||++f);this.active=this._findActive(d.active).addClass("ui-accordion-header-active").removeClass("ui-corner-all");this.active.next().addClass("ui-accordion-content-active").show();this.headers.attr("role","tab").each(function(a){var d=b(this),c=d.attr("id"),e=d.next(),f=e.attr("id");c||(c=g+"-header-"+a,d.attr("id",c));f||(f=g+"-panel-"+a,e.attr("id",f));d.attr("aria-controls",
f);e.attr("aria-labelledby",c)}).next().attr("role","tabpanel");this.headers.not(this.active).attr({"aria-selected":"false",tabIndex:-1}).next().attr({"aria-expanded":"false","aria-hidden":"true"}).hide();this.active.length?this.active.attr({"aria-selected":"true",tabIndex:0}).next().attr({"aria-expanded":"true","aria-hidden":"false"}):this.headers.eq(0).attr("tabIndex",0);this._createIcons();this._setupEvents(d.event);"fill"===c?(a=e.height(),this.element.siblings(":visible").each(function(){var d=
b(this),c=d.css("position");"absolute"!==c&&"fixed"!==c&&(a-=d.outerHeight(!0))}),this.headers.each(function(){a-=b(this).outerHeight(!0)}),this.headers.next().each(function(){b(this).height(Math.max(0,a-b(this).innerHeight()+b(this).height()))}).css("overflow","auto")):"auto"===c&&(a=0,this.headers.next().each(function(){a=Math.max(a,b(this).css("height","").height())}).height(a))},_activate:function(a){a=this._findActive(a)[0];a!==this.active[0]&&(a=a||this.active[0],this._eventHandler({target:a,
currentTarget:a,preventDefault:b.noop}))},_findActive:function(a){return"number"===typeof a?this.headers.eq(a):b()},_setupEvents:function(a){var d={keydown:"_keydown"};a&&b.each(a.split(" "),function(a,b){d[b]="_eventHandler"});this._off(this.headers.add(this.headers.next()));this._on(this.headers,d);this._on(this.headers.next(),{keydown:"_panelKeyDown"});this._hoverable(this.headers);this._focusable(this.headers)},_eventHandler:function(a){var d=this.options,c=this.active,e=b(a.currentTarget),f=
e[0]===c[0],h=f&&d.collapsible,g=h?b():e.next(),s=c.next(),g={oldHeader:c,oldPanel:s,newHeader:h?b():e,newPanel:g};a.preventDefault();f&&!d.collapsible||!1===this._trigger("beforeActivate",a,g)||(d.active=h?!1:this.headers.index(e),this.active=f?b():e,this._toggle(g),c.removeClass("ui-accordion-header-active ui-state-active"),d.icons&&c.children(".ui-accordion-header-icon").removeClass(d.icons.activeHeader).addClass(d.icons.header),f||(e.removeClass("ui-corner-all").addClass("ui-accordion-header-active ui-state-active ui-corner-top"),
d.icons&&e.children(".ui-accordion-header-icon").removeClass(d.icons.header).addClass(d.icons.activeHeader),e.next().addClass("ui-accordion-content-active")))},_toggle:function(a){var d=a.newPanel,c=this.prevShow.length?this.prevShow:a.oldPanel;this.prevShow.add(this.prevHide).stop(!0,!0);this.prevShow=d;this.prevHide=c;this.options.animate?this._animate(d,c,a):(c.hide(),d.show(),this._toggleComplete(a));c.attr({"aria-expanded":"false","aria-hidden":"true"});c.prev().attr("aria-selected","false");
d.length&&c.length?c.prev().attr("tabIndex",-1):d.length&&this.headers.filter(function(){return 0===b(this).attr("tabIndex")}).attr("tabIndex",-1);d.attr({"aria-expanded":"true","aria-hidden":"false"}).prev().attr({"aria-selected":"true",tabIndex:0})},_animate:function(a,b,f){var e,l,h,m=this,s=0,n=a.length&&(!b.length||a.index()<b.index()),r=this.options.animate||{},n=n&&r.down||r,q=function(){m._toggleComplete(f)};"number"===typeof n&&(h=n);"string"===typeof n&&(l=n);l=l||n.easing||r.easing;h=h||
n.duration||r.duration;if(!b.length)return a.animate(c,h,l,q);if(!a.length)return b.animate(g,h,l,q);e=a.show().outerHeight();b.animate(g,{duration:h,easing:l,step:function(a,b){b.now=Math.round(a)}});a.hide().animate(c,{duration:h,easing:l,complete:q,step:function(a,c){c.now=Math.round(a);"height"!==c.prop?s+=c.now:"content"!==m.options.heightStyle&&(c.now=Math.round(e-b.outerHeight()-s),s=0)}})},_toggleComplete:function(a){var b=a.oldPanel;b.removeClass("ui-accordion-content-active").prev().removeClass("ui-corner-top").addClass("ui-corner-all");
b.length&&(b.parent()[0].className=b.parent()[0].className);this._trigger("activate",null,a)}})})(jQuery);
(function(b,p){var f,g,c,a,d=function(){var a=b(this);setTimeout(function(){a.find(":ui-button").button("refresh")},1)},k=function(a){var c=a.name,d=a.form,f=b([]);c&&(c=c.replace(/'/g,"\\'"),f=d?b(d).find("[name='"+c+"']"):b("[name='"+c+"']",a.ownerDocument).filter(function(){return!this.form}));return f};b.widget("ui.button",{version:"1.10.3",defaultElement:"<button>",options:{disabled:null,text:!0,label:null,icons:{primary:null,secondary:null}},_create:function(){this.element.closest("form").unbind("reset"+
this.eventNamespace).bind("reset"+this.eventNamespace,d);"boolean"!==typeof this.options.disabled?this.options.disabled=!!this.element.prop("disabled"):this.element.prop("disabled",this.options.disabled);this._determineButtonType();this.hasTitle=!!this.buttonElement.attr("title");var e=this,l=this.options,h="checkbox"===this.type||"radio"===this.type,m=h?"":"ui-state-active";null===l.label&&(l.label="input"===this.type?this.buttonElement.val():this.buttonElement.html());this._hoverable(this.buttonElement);
this.buttonElement.addClass("ui-button ui-widget ui-state-default ui-corner-all").attr("role","button").bind("mouseenter"+this.eventNamespace,function(){l.disabled||this===f&&b(this).addClass("ui-state-active")}).bind("mouseleave"+this.eventNamespace,function(){l.disabled||b(this).removeClass(m)}).bind("click"+this.eventNamespace,function(a){l.disabled&&(a.preventDefault(),a.stopImmediatePropagation())});this.element.bind("focus"+this.eventNamespace,function(){e.buttonElement.addClass("ui-state-focus")}).bind("blur"+
this.eventNamespace,function(){e.buttonElement.removeClass("ui-state-focus")});h&&(this.element.bind("change"+this.eventNamespace,function(){a||e.refresh()}),this.buttonElement.bind("mousedown"+this.eventNamespace,function(b){l.disabled||(a=!1,g=b.pageX,c=b.pageY)}).bind("mouseup"+this.eventNamespace,function(b){l.disabled||g===b.pageX&&c===b.pageY||(a=!0)}));"checkbox"===this.type?this.buttonElement.bind("click"+this.eventNamespace,function(){if(l.disabled||a)return!1}):"radio"===this.type?this.buttonElement.bind("click"+
this.eventNamespace,function(){if(l.disabled||a)return!1;b(this).addClass("ui-state-active");e.buttonElement.attr("aria-pressed","true");var c=e.element[0];k(c).not(c).map(function(){return b(this).button("widget")[0]}).removeClass("ui-state-active").attr("aria-pressed","false")}):(this.buttonElement.bind("mousedown"+this.eventNamespace,function(){if(l.disabled)return!1;b(this).addClass("ui-state-active");f=this;e.document.one("mouseup",function(){f=null})}).bind("mouseup"+this.eventNamespace,function(){if(l.disabled)return!1;
b(this).removeClass("ui-state-active")}).bind("keydown"+this.eventNamespace,function(a){if(l.disabled)return!1;a.keyCode!==b.ui.keyCode.SPACE&&a.keyCode!==b.ui.keyCode.ENTER||b(this).addClass("ui-state-active")}).bind("keyup"+this.eventNamespace+" blur"+this.eventNamespace,function(){b(this).removeClass("ui-state-active")}),this.buttonElement.is("a")&&this.buttonElement.keyup(function(a){a.keyCode===b.ui.keyCode.SPACE&&b(this).click()}));this._setOption("disabled",l.disabled);this._resetButton()},
_determineButtonType:function(){var a,b;this.element.is("[type=checkbox]")?this.type="checkbox":this.element.is("[type=radio]")?this.type="radio":this.element.is("input")?this.type="input":this.type="button";"checkbox"===this.type||"radio"===this.type?(a=this.element.parents().last(),b="label[for='"+this.element.attr("id")+"']",this.buttonElement=a.find(b),this.buttonElement.length||(a=a.length?a.siblings():this.element.siblings(),this.buttonElement=a.filter(b),this.buttonElement.length||(this.buttonElement=
a.find(b))),this.element.addClass("ui-helper-hidden-accessible"),(a=this.element.is(":checked"))&&this.buttonElement.addClass("ui-state-active"),this.buttonElement.prop("aria-pressed",a)):this.buttonElement=this.element},widget:function(){return this.buttonElement},_destroy:function(){this.element.removeClass("ui-helper-hidden-accessible");this.buttonElement.removeClass("ui-button ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-active  ui-button-icons-only ui-button-icon-only ui-button-text-icons ui-button-text-icon-primary ui-button-text-icon-secondary ui-button-text-only").removeAttr("role").removeAttr("aria-pressed").html(this.buttonElement.find(".ui-button-text").html());
this.hasTitle||this.buttonElement.removeAttr("title")},_setOption:function(a,b){this._super(a,b);"disabled"===a?b?this.element.prop("disabled",!0):this.element.prop("disabled",!1):this._resetButton()},refresh:function(){var a=this.element.is("input, button")?this.element.is(":disabled"):this.element.hasClass("ui-button-disabled");a!==this.options.disabled&&this._setOption("disabled",a);"radio"===this.type?k(this.element[0]).each(function(){b(this).is(":checked")?b(this).button("widget").addClass("ui-state-active").attr("aria-pressed",
"true"):b(this).button("widget").removeClass("ui-state-active").attr("aria-pressed","false")}):"checkbox"===this.type&&(this.element.is(":checked")?this.buttonElement.addClass("ui-state-active").attr("aria-pressed","true"):this.buttonElement.removeClass("ui-state-active").attr("aria-pressed","false"))},_resetButton:function(){if("input"===this.type)this.options.label&&this.element.val(this.options.label);else{var a=this.buttonElement.removeClass("ui-button-icons-only ui-button-icon-only ui-button-text-icons ui-button-text-icon-primary ui-button-text-icon-secondary ui-button-text-only"),
c=b("<span></span>",this.document[0]).addClass("ui-button-text").html(this.options.label).appendTo(a.empty()).text(),d=this.options.icons,f=d.primary&&d.secondary,k=[];d.primary||d.secondary?(this.options.text&&k.push("ui-button-text-icon"+(f?"s":d.primary?"-primary":"-secondary")),d.primary&&a.prepend("<span class='ui-button-icon-primary ui-icon "+d.primary+"'></span>"),d.secondary&&a.append("<span class='ui-button-icon-secondary ui-icon "+d.secondary+"'></span>"),this.options.text||(k.push(f?"ui-button-icons-only":
"ui-button-icon-only"),this.hasTitle||a.attr("title",b.trim(c)))):k.push("ui-button-text-only");a.addClass(k.join(" "))}}});b.widget("ui.buttonset",{version:"1.10.3",options:{items:"button, input[type=button], input[type=submit], input[type=reset], input[type=checkbox], input[type=radio], a, :data(ui-button)"},_create:function(){this.element.addClass("ui-buttonset")},_init:function(){this.refresh()},_setOption:function(a,b){"disabled"===a&&this.buttons.button("option",a,b);this._super(a,b)},refresh:function(){var a=
"rtl"===this.element.css("direction");this.buttons=this.element.find(this.options.items).filter(":ui-button").button("refresh").end().not(":ui-button").button().end().map(function(){return b(this).button("widget")[0]}).removeClass("ui-corner-all ui-corner-left ui-corner-right").filter(":first").addClass(a?"ui-corner-right":"ui-corner-left").end().filter(":last").addClass(a?"ui-corner-left":"ui-corner-right").end().end()},_destroy:function(){this.element.removeClass("ui-buttonset");this.buttons.map(function(){return b(this).button("widget")[0]}).removeClass("ui-corner-left ui-corner-right").end().button("destroy")}})})(jQuery);
(function(b,p){b.widget("ui.slider",b.ui.mouse,{version:"1.10.3",widgetEventPrefix:"slide",options:{animate:!1,distance:0,max:100,min:0,orientation:"horizontal",range:!1,step:1,value:0,values:null,change:null,slide:null,start:null,stop:null},_create:function(){this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this.element.addClass("ui-slider ui-slider-"+this.orientation+" ui-widget ui-widget-content ui-corner-all");this._refresh();
this._setOption("disabled",this.options.disabled);this._animateOff=!1},_refresh:function(){this._createRange();this._createHandles();this._setupEvents();this._refreshValue()},_createHandles:function(){var f,g;f=this.options;var c=this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),a=[];g=f.values&&f.values.length||1;c.length>g&&(c.slice(g).remove(),c=c.slice(0,g));for(f=c.length;f<g;f++)a.push("<a class='ui-slider-handle ui-state-default ui-corner-all' href='#'></a>");
this.handles=c.add(b(a.join("")).appendTo(this.element));this.handle=this.handles.eq(0);this.handles.each(function(a){b(this).data("ui-slider-handle-index",a)})},_createRange:function(){var f=this.options,g="";f.range?(!0===f.range&&(f.values?f.values.length&&2!==f.values.length?f.values=[f.values[0],f.values[0]]:b.isArray(f.values)&&(f.values=f.values.slice(0)):f.values=[this._valueMin(),this._valueMin()]),this.range&&this.range.length?this.range.removeClass("ui-slider-range-min ui-slider-range-max").css({left:"",
bottom:""}):(this.range=b("<div></div>").appendTo(this.element),g="ui-slider-range ui-widget-header ui-corner-all"),this.range.addClass(g+("min"===f.range||"max"===f.range?" ui-slider-range-"+f.range:""))):this.range=b([])},_setupEvents:function(){var b=this.handles.add(this.range).filter("a");this._off(b);this._on(b,this._handleEvents);this._hoverable(b);this._focusable(b)},_destroy:function(){this.handles.remove();this.range.remove();this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-widget ui-widget-content ui-corner-all");
this._mouseDestroy()},_mouseCapture:function(f){var g,c,a,d,k,e=this,l=this.options;if(l.disabled)return!1;this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()};this.elementOffset=this.element.offset();g=this._normValueFromMouse({x:f.pageX,y:f.pageY});c=this._valueMax()-this._valueMin()+1;this.handles.each(function(f){var k=Math.abs(g-e.values(f));if(c>k||c===k&&(f===e._lastChangedValue||e.values(f)===l.min))c=k,a=b(this),d=f});if(!1===this._start(f,d))return!1;this._mouseSliding=
!0;this._handleIndex=d;a.addClass("ui-state-active").focus();k=a.offset();this._clickOffset=b(f.target).parents().addBack().is(".ui-slider-handle")?{left:f.pageX-k.left-a.width()/2,top:f.pageY-k.top-a.height()/2-(parseInt(a.css("borderTopWidth"),10)||0)-(parseInt(a.css("borderBottomWidth"),10)||0)+(parseInt(a.css("marginTop"),10)||0)}:{left:0,top:0};this.handles.hasClass("ui-state-hover")||this._slide(f,d,g);return this._animateOff=!0},_mouseStart:function(){return!0},_mouseDrag:function(b){var g=
this._normValueFromMouse({x:b.pageX,y:b.pageY});this._slide(b,this._handleIndex,g);return!1},_mouseStop:function(b){this.handles.removeClass("ui-state-active");this._mouseSliding=!1;this._stop(b,this._handleIndex);this._change(b,this._handleIndex);this._clickOffset=this._handleIndex=null;return this._animateOff=!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(b){var g;"horizontal"===this.orientation?(g=this.elementSize.width,
b=b.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(g=this.elementSize.height,b=b.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0));g=b/g;1<g&&(g=1);0>g&&(g=0);"vertical"===this.orientation&&(g=1-g);b=this._valueMax()-this._valueMin();g=this._valueMin()+g*b;return this._trimAlignValue(g)},_start:function(b,g){var c={handle:this.handles[g],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(g),c.values=this.values());
return this._trigger("start",b,c)},_slide:function(b,g,c){var a;this.options.values&&this.options.values.length?(a=this.values(g?0:1),2===this.options.values.length&&!0===this.options.range&&(0===g&&c>a||1===g&&c<a)&&(c=a),c!==this.values(g)&&(a=this.values(),a[g]=c,b=this._trigger("slide",b,{handle:this.handles[g],value:c,values:a}),this.values(g?0:1),!1!==b&&this.values(g,c,!0))):c!==this.value()&&(b=this._trigger("slide",b,{handle:this.handles[g],value:c}),!1!==b&&this.value(c))},_stop:function(b,
g){var c={handle:this.handles[g],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(g),c.values=this.values());this._trigger("stop",b,c)},_change:function(b,g){if(!this._keySliding&&!this._mouseSliding){var c={handle:this.handles[g],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(g),c.values=this.values());this._lastChangedValue=g;this._trigger("change",b,c)}},value:function(b){if(arguments.length)this.options.value=
this._trimAlignValue(b),this._refreshValue(),this._change(null,0);else return this._value()},values:function(f,g){var c,a,d;if(1<arguments.length)this.options.values[f]=this._trimAlignValue(g),this._refreshValue(),this._change(null,f);else if(arguments.length)if(b.isArray(arguments[0])){c=this.options.values;a=arguments[0];for(d=0;d<c.length;d+=1)c[d]=this._trimAlignValue(a[d]),this._change(null,d);this._refreshValue()}else return this.options.values&&this.options.values.length?this._values(f):this.value();
else return this._values()},_setOption:function(f,g){var c,a=0;"range"===f&&!0===this.options.range&&("min"===g?(this.options.value=this._values(0),this.options.values=null):"max"===g&&(this.options.value=this._values(this.options.values.length-1),this.options.values=null));b.isArray(this.options.values)&&(a=this.options.values.length);b.Widget.prototype._setOption.apply(this,arguments);switch(f){case "orientation":this._detectOrientation();this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-"+
this.orientation);this._refreshValue();break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(c=0;c<a;c+=1)this._change(null,c);this._animateOff=!1;break;case "min":case "max":this._animateOff=!0;this._refreshValue();this._animateOff=!1;break;case "range":this._animateOff=!0,this._refresh(),this._animateOff=!1}},_value:function(){var b=this.options.value;return b=this._trimAlignValue(b)},
_values:function(b){var g,c;if(arguments.length)return g=this.options.values[b],g=this._trimAlignValue(g);if(this.options.values&&this.options.values.length){g=this.options.values.slice();for(c=0;c<g.length;c+=1)g[c]=this._trimAlignValue(g[c]);return g}return[]},_trimAlignValue:function(b){if(b<=this._valueMin())return this._valueMin();if(b>=this._valueMax())return this._valueMax();var g=0<this.options.step?this.options.step:1,c=(b-this._valueMin())%g;b-=c;2*Math.abs(c)>=g&&(b+=0<c?g:-g);return parseFloat(b.toFixed(5))},
_valueMin:function(){return this.options.min},_valueMax:function(){return this.options.max},_refreshValue:function(){var f,g,c,a,d,k=this.options.range,e=this.options,l=this,h=this._animateOff?!1:e.animate,m={};if(this.options.values&&this.options.values.length)this.handles.each(function(a){g=100*((l.values(a)-l._valueMin())/(l._valueMax()-l._valueMin()));m["horizontal"===l.orientation?"left":"bottom"]=g+"%";b(this).stop(1,1)[h?"animate":"css"](m,e.animate);if(!0===l.options.range)if("horizontal"===
l.orientation){if(0===a)l.range.stop(1,1)[h?"animate":"css"]({left:g+"%"},e.animate);if(1===a)l.range[h?"animate":"css"]({width:g-f+"%"},{queue:!1,duration:e.animate})}else{if(0===a)l.range.stop(1,1)[h?"animate":"css"]({bottom:g+"%"},e.animate);if(1===a)l.range[h?"animate":"css"]({height:g-f+"%"},{queue:!1,duration:e.animate})}f=g});else{c=this.value();a=this._valueMin();d=this._valueMax();g=d!==a?100*((c-a)/(d-a)):0;m["horizontal"===this.orientation?"left":"bottom"]=g+"%";this.handle.stop(1,1)[h?
"animate":"css"](m,e.animate);if("min"===k&&"horizontal"===this.orientation)this.range.stop(1,1)[h?"animate":"css"]({width:g+"%"},e.animate);if("max"===k&&"horizontal"===this.orientation)this.range[h?"animate":"css"]({width:100-g+"%"},{queue:!1,duration:e.animate});if("min"===k&&"vertical"===this.orientation)this.range.stop(1,1)[h?"animate":"css"]({height:g+"%"},e.animate);if("max"===k&&"vertical"===this.orientation)this.range[h?"animate":"css"]({height:100-g+"%"},{queue:!1,duration:e.animate})}},
_handleEvents:{keydown:function(f){var g,c,a,d=b(f.target).data("ui-slider-handle-index");switch(f.keyCode){case b.ui.keyCode.HOME:case b.ui.keyCode.END:case b.ui.keyCode.PAGE_UP:case b.ui.keyCode.PAGE_DOWN:case b.ui.keyCode.UP:case b.ui.keyCode.RIGHT:case b.ui.keyCode.DOWN:case b.ui.keyCode.LEFT:if(f.preventDefault(),!this._keySliding&&(this._keySliding=!0,b(f.target).addClass("ui-state-active"),g=this._start(f,d),!1===g))return}a=this.options.step;g=this.options.values&&this.options.values.length?
c=this.values(d):c=this.value();switch(f.keyCode){case b.ui.keyCode.HOME:c=this._valueMin();break;case b.ui.keyCode.END:c=this._valueMax();break;case b.ui.keyCode.PAGE_UP:c=this._trimAlignValue(g+(this._valueMax()-this._valueMin())/5);break;case b.ui.keyCode.PAGE_DOWN:c=this._trimAlignValue(g-(this._valueMax()-this._valueMin())/5);break;case b.ui.keyCode.UP:case b.ui.keyCode.RIGHT:if(g===this._valueMax())return;c=this._trimAlignValue(g+a);break;case b.ui.keyCode.DOWN:case b.ui.keyCode.LEFT:if(g===
this._valueMin())return;c=this._trimAlignValue(g-a)}this._slide(f,d,c)},click:function(b){b.preventDefault()},keyup:function(f){var g=b(f.target).data("ui-slider-handle-index");this._keySliding&&(this._keySliding=!1,this._stop(f,g),this._change(f,g),b(f.target).removeClass("ui-state-active"))}}})})(jQuery);
(function(b,p){function f(a){return 1<a.hash.length&&decodeURIComponent(a.href.replace(c,""))===decodeURIComponent(location.href.replace(c,""))}var g=0,c=/#.*$/;b.widget("ui.tabs",{version:"1.10.3",delay:300,options:{active:null,collapsible:!1,event:"click",heightStyle:"content",hide:null,show:null,activate:null,beforeActivate:null,beforeLoad:null,load:null},_create:function(){var a=this,c=this.options;this.running=!1;this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all").toggleClass("ui-tabs-collapsible",
c.collapsible).delegate(".ui-tabs-nav > li","mousedown"+this.eventNamespace,function(a){b(this).is(".ui-state-disabled")&&a.preventDefault()}).delegate(".ui-tabs-anchor","focus"+this.eventNamespace,function(){b(this).closest("li").is(".ui-state-disabled")&&this.blur()});this._processTabs();c.active=this._initialActive();b.isArray(c.disabled)&&(c.disabled=b.unique(c.disabled.concat(b.map(this.tabs.filter(".ui-state-disabled"),function(b){return a.tabs.index(b)}))).sort());this.active=!1!==this.options.active&&
this.anchors.length?this._findActive(c.active):b();this._refresh();this.active.length&&this.load(c.active)},_initialActive:function(){var a=this.options.active,c=this.options.collapsible,f=location.hash.substring(1);null===a&&(f&&this.tabs.each(function(c,d){if(b(d).attr("aria-controls")===f)return a=c,!1}),null===a&&(a=this.tabs.index(this.tabs.filter(".ui-tabs-active"))),null===a||-1===a)&&(a=this.tabs.length?0:!1);!1!==a&&(a=this.tabs.index(this.tabs.eq(a)),-1===a&&(a=c?!1:0));!c&&(!1===a&&this.anchors.length)&&
(a=0);return a},_getCreateEventData:function(){return{tab:this.active,panel:this.active.length?this._getPanelForTab(this.active):b()}},_tabKeydown:function(a){var c=b(this.document[0].activeElement).closest("li"),f=this.tabs.index(c),e=!0;if(!this._handlePageNav(a)){switch(a.keyCode){case b.ui.keyCode.RIGHT:case b.ui.keyCode.DOWN:f++;break;case b.ui.keyCode.UP:case b.ui.keyCode.LEFT:e=!1;f--;break;case b.ui.keyCode.END:f=this.anchors.length-1;break;case b.ui.keyCode.HOME:f=0;break;case b.ui.keyCode.SPACE:a.preventDefault();
clearTimeout(this.activating);this._activate(f);return;case b.ui.keyCode.ENTER:a.preventDefault();clearTimeout(this.activating);this._activate(f===this.options.active?!1:f);return;default:return}a.preventDefault();clearTimeout(this.activating);f=this._focusNextTab(f,e);a.ctrlKey||(c.attr("aria-selected","false"),this.tabs.eq(f).attr("aria-selected","true"),this.activating=this._delay(function(){this.option("active",f)},this.delay))}},_panelKeydown:function(a){!this._handlePageNav(a)&&(a.ctrlKey&&
a.keyCode===b.ui.keyCode.UP)&&(a.preventDefault(),this.active.focus())},_handlePageNav:function(a){if(a.altKey&&a.keyCode===b.ui.keyCode.PAGE_UP)return this._activate(this._focusNextTab(this.options.active-1,!1)),!0;if(a.altKey&&a.keyCode===b.ui.keyCode.PAGE_DOWN)return this._activate(this._focusNextTab(this.options.active+1,!0)),!0},_findNextTab:function(a,c){function f(){a>e&&(a=0);0>a&&(a=e);return a}for(var e=this.tabs.length-1;-1!==b.inArray(f(),this.options.disabled);)a=c?a+1:a-1;return a},
_focusNextTab:function(a,b){a=this._findNextTab(a,b);this.tabs.eq(a).focus();return a},_setOption:function(a,b){"active"===a?this._activate(b):"disabled"===a?this._setupDisabled(b):(this._super(a,b),"collapsible"===a&&(this.element.toggleClass("ui-tabs-collapsible",b),b||!1!==this.options.active||this._activate(0)),"event"===a&&this._setupEvents(b),"heightStyle"===a&&this._setupHeightStyle(b))},_tabId:function(a){return a.attr("aria-controls")||"ui-tabs-"+ ++g},_sanitizeSelector:function(a){return a?
a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$&"):""},refresh:function(){var a=this.options,c=this.tablist.children(":has(a[href])");a.disabled=b.map(c.filter(".ui-state-disabled"),function(a){return c.index(a)});this._processTabs();!1!==a.active&&this.anchors.length?this.active.length&&!b.contains(this.tablist[0],this.active[0])?this.tabs.length===a.disabled.length?(a.active=!1,this.active=b()):this._activate(this._findNextTab(Math.max(0,a.active-1),!1)):a.active=this.tabs.index(this.active):
(a.active=!1,this.active=b());this._refresh()},_refresh:function(){this._setupDisabled(this.options.disabled);this._setupEvents(this.options.event);this._setupHeightStyle(this.options.heightStyle);this.tabs.not(this.active).attr({"aria-selected":"false",tabIndex:-1});this.panels.not(this._getPanelForTab(this.active)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});this.active.length?(this.active.addClass("ui-tabs-active ui-state-active").attr({"aria-selected":"true",tabIndex:0}),this._getPanelForTab(this.active).show().attr({"aria-expanded":"true",
"aria-hidden":"false"})):this.tabs.eq(0).attr("tabIndex",0)},_processTabs:function(){var a=this;this.tablist=this._getList().addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all").attr("role","tablist");this.tabs=this.tablist.find("> li:has(a[href])").addClass("ui-state-default ui-corner-top").attr({role:"tab",tabIndex:-1});this.anchors=this.tabs.map(function(){return b("a",this)[0]}).addClass("ui-tabs-anchor").attr({role:"presentation",tabIndex:-1});this.panels=
b();this.anchors.each(function(c,k){var e,g,h,m=b(k).uniqueId().attr("id"),s=b(k).closest("li"),n=s.attr("aria-controls");f(k)?(e=k.hash,g=a.element.find(a._sanitizeSelector(e))):(h=a._tabId(s),e="#"+h,g=a.element.find(e),g.length||(g=a._createPanel(h),g.insertAfter(a.panels[c-1]||a.tablist)),g.attr("aria-live","polite"));g.length&&(a.panels=a.panels.add(g));n&&s.data("ui-tabs-aria-controls",n);s.attr({"aria-controls":e.substring(1),"aria-labelledby":m});g.attr("aria-labelledby",m)});this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").attr("role",
"tabpanel")},_getList:function(){return this.element.find("ol,ul").eq(0)},_createPanel:function(a){return b("<div>").attr("id",a).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").data("ui-tabs-destroy",!0)},_setupDisabled:function(a){b.isArray(a)&&(a.length?a.length===this.anchors.length&&(a=!0):a=!1);for(var c=0,f;f=this.tabs[c];c++)!0===a||-1!==b.inArray(c,a)?b(f).addClass("ui-state-disabled").attr("aria-disabled","true"):b(f).removeClass("ui-state-disabled").removeAttr("aria-disabled");
this.options.disabled=a},_setupEvents:function(a){var c={click:function(a){a.preventDefault()}};a&&b.each(a.split(" "),function(a,b){c[b]="_eventHandler"});this._off(this.anchors.add(this.tabs).add(this.panels));this._on(this.anchors,c);this._on(this.tabs,{keydown:"_tabKeydown"});this._on(this.panels,{keydown:"_panelKeydown"});this._focusable(this.tabs);this._hoverable(this.tabs)},_setupHeightStyle:function(a){var c,f=this.element.parent();"fill"===a?(c=f.height(),c-=this.element.outerHeight()-this.element.height(),
this.element.siblings(":visible").each(function(){var a=b(this),f=a.css("position");"absolute"!==f&&"fixed"!==f&&(c-=a.outerHeight(!0))}),this.element.children().not(this.panels).each(function(){c-=b(this).outerHeight(!0)}),this.panels.each(function(){b(this).height(Math.max(0,c-b(this).innerHeight()+b(this).height()))}).css("overflow","auto")):"auto"===a&&(c=0,this.panels.each(function(){c=Math.max(c,b(this).height("").height())}).height(c))},_eventHandler:function(a){var c=this.options,f=this.active,
e=b(a.currentTarget).closest("li"),g=e[0]===f[0],h=g&&c.collapsible,m=h?b():this._getPanelForTab(e),s=f.length?this._getPanelForTab(f):b(),f={oldTab:f,oldPanel:s,newTab:h?b():e,newPanel:m};a.preventDefault();e.hasClass("ui-state-disabled")||(e.hasClass("ui-tabs-loading")||this.running||g&&!c.collapsible||!1===this._trigger("beforeActivate",a,f))||(c.active=h?!1:this.tabs.index(e),this.active=g?b():e,this.xhr&&this.xhr.abort(),s.length||m.length||b.error("jQuery UI Tabs: Mismatching fragment identifier."),
m.length&&this.load(this.tabs.index(e),a),this._toggle(a,f))},_toggle:function(a,c){function f(){g.running=!1;g._trigger("activate",a,c)}function e(){c.newTab.closest("li").addClass("ui-tabs-active ui-state-active");h.length&&g.options.show?g._show(h,g.options.show,f):(h.show(),f())}var g=this,h=c.newPanel,m=c.oldPanel;this.running=!0;m.length&&this.options.hide?this._hide(m,this.options.hide,function(){c.oldTab.closest("li").removeClass("ui-tabs-active ui-state-active");e()}):(c.oldTab.closest("li").removeClass("ui-tabs-active ui-state-active"),
m.hide(),e());m.attr({"aria-expanded":"false","aria-hidden":"true"});c.oldTab.attr("aria-selected","false");h.length&&m.length?c.oldTab.attr("tabIndex",-1):h.length&&this.tabs.filter(function(){return 0===b(this).attr("tabIndex")}).attr("tabIndex",-1);h.attr({"aria-expanded":"true","aria-hidden":"false"});c.newTab.attr({"aria-selected":"true",tabIndex:0})},_activate:function(a){a=this._findActive(a);a[0]!==this.active[0]&&(a.length||(a=this.active),a=a.find(".ui-tabs-anchor")[0],this._eventHandler({target:a,
currentTarget:a,preventDefault:b.noop}))},_findActive:function(a){return!1===a?b():this.tabs.eq(a)},_getIndex:function(a){"string"===typeof a&&(a=this.anchors.index(this.anchors.filter("[href$='"+a+"']")));return a},_destroy:function(){this.xhr&&this.xhr.abort();this.element.removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible");this.tablist.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all").removeAttr("role");this.anchors.removeClass("ui-tabs-anchor").removeAttr("role").removeAttr("tabIndex").removeUniqueId();
this.tabs.add(this.panels).each(function(){b.data(this,"ui-tabs-destroy")?b(this).remove():b(this).removeClass("ui-state-default ui-state-active ui-state-disabled ui-corner-top ui-corner-bottom ui-widget-content ui-tabs-active ui-tabs-panel").removeAttr("tabIndex").removeAttr("aria-live").removeAttr("aria-busy").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-expanded").removeAttr("role")});this.tabs.each(function(){var a=b(this),c=a.data("ui-tabs-aria-controls");
c?a.attr("aria-controls",c).removeData("ui-tabs-aria-controls"):a.removeAttr("aria-controls")});this.panels.show();"content"!==this.options.heightStyle&&this.panels.css("height","")},enable:function(a){var c=this.options.disabled;!1!==c&&(a===p?c=!1:(a=this._getIndex(a),c=b.isArray(c)?b.map(c,function(b){return b!==a?b:null}):b.map(this.tabs,function(b,c){return c!==a?c:null})),this._setupDisabled(c))},disable:function(a){var c=this.options.disabled;if(!0!==c){if(a===p)c=!0;else{a=this._getIndex(a);
if(-1!==b.inArray(a,c))return;c=b.isArray(c)?b.merge([a],c).sort():[a]}this._setupDisabled(c)}},load:function(a,c){a=this._getIndex(a);var g=this,e=this.tabs.eq(a),l=e.find(".ui-tabs-anchor"),h=this._getPanelForTab(e),m={tab:e,panel:h};f(l[0])||(this.xhr=b.ajax(this._ajaxSettings(l,c,m)))&&"canceled"!==this.xhr.statusText&&(e.addClass("ui-tabs-loading"),h.attr("aria-busy","true"),this.xhr.success(function(a){setTimeout(function(){h.html(a);g._trigger("load",c,m)},1)}).complete(function(a,b){setTimeout(function(){"abort"===
b&&g.panels.stop(!1,!0);e.removeClass("ui-tabs-loading");h.removeAttr("aria-busy");a===g.xhr&&delete g.xhr},1)}))},_ajaxSettings:function(a,c,f){var e=this;return{url:a.attr("href"),beforeSend:function(a,g){return e._trigger("beforeLoad",c,b.extend({jqXHR:a,ajaxSettings:g},f))}}},_getPanelForTab:function(a){a=b(a).attr("aria-controls");return this.element.find(this._sanitizeSelector("#"+a))}})})(jQuery);
(function(b,p){b.effects={effect:{}};(function(b,g){function c(a,b,c){var d=m[b.type]||{};if(null==a)return c||!b.def?null:b.def;a=d.floor?~~a:parseFloat(a);return isNaN(a)?b.def:d.mod?(a+d.mod)%d.mod:0>a?0:d.max<a?d.max:a}function a(a){var c=l(),d=c._rgba=[];a=a.toLowerCase();q(e,function(b,e){var f,g=e.re.exec(a);f=g&&e.parse(g);g=e.space||"rgba";if(f)return f=c[g](f),c[h[g].cache]=f[h[g].cache],d=c._rgba=f._rgba,!1});return d.length?("0,0,0,0"===d.join()&&b.extend(d,r.transparent),c):r[a]}function d(a,
b,c){c=(c+1)%1;return 1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+6*(b-a)*(2/3-c):a}var k=/^([\-+])=\s*(\d+\.?\d*)/,e=[{re:/rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*(\d?(?:\.\d+)?)\s*)?\)/,parse:function(a){return[a[1],a[2],a[3],a[4]]}},{re:/rgba?\(\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*(?:,\s*(\d?(?:\.\d+)?)\s*)?\)/,parse:function(a){return[2.55*a[1],2.55*a[2],2.55*a[3],a[4]]}},{re:/#([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})/,parse:function(a){return[parseInt(a[1],
16),parseInt(a[2],16),parseInt(a[3],16)]}},{re:/#([a-f0-9])([a-f0-9])([a-f0-9])/,parse:function(a){return[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]}},{re:/hsla?\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*(?:,\s*(\d?(?:\.\d+)?)\s*)?\)/,space:"hsla",parse:function(a){return[a[1],a[2]/100,a[3]/100,a[4]]}}],l=b.Color=function(a,c,d,e){return new b.Color.fn.parse(a,c,d,e)},h={rgba:{props:{red:{idx:0,type:"byte"},green:{idx:1,type:"byte"},blue:{idx:2,
type:"byte"}}},hsla:{props:{hue:{idx:0,type:"degrees"},saturation:{idx:1,type:"percent"},lightness:{idx:2,type:"percent"}}}},m={"byte":{floor:!0,max:255},percent:{max:1},degrees:{mod:360,floor:!0}},s=l.support={},n=b("<p>")[0],r,q=b.each;n.style.cssText="background-color:rgba(1,1,1,.5)";s.rgba=-1<n.style.backgroundColor.indexOf("rgba");q(h,function(a,b){b.cache="_"+a;b.props.alpha={idx:3,type:"percent",def:1}});l.fn=b.extend(l.prototype,{parse:function(d,e,k,t){if(d===g)return this._rgba=[null,null,
null,null],this;if(d.jquery||d.nodeType)d=b(d).css(e),e=g;var m=this,n=b.type(d),A=this._rgba=[];e!==g&&(d=[d,e,k,t],n="array");if("string"===n)return this.parse(a(d)||r._default);if("array"===n)return q(h.rgba.props,function(a,b){A[b.idx]=c(d[b.idx],b)}),this;if("object"===n)return d instanceof l?q(h,function(a,b){d[b.cache]&&(m[b.cache]=d[b.cache].slice())}):q(h,function(a,e){var g=e.cache;q(e.props,function(a,b){if(!m[g]&&e.to){if("alpha"===a||null==d[a])return;m[g]=e.to(m._rgba)}m[g][b.idx]=c(d[a],
b,!0)});m[g]&&0>b.inArray(null,m[g].slice(0,3))&&(m[g][3]=1,e.from&&(m._rgba=e.from(m[g])))}),this},is:function(a){var b=l(a),c=!0,d=this;q(h,function(a,e){var f,g=b[e.cache];g&&(f=d[e.cache]||e.to&&e.to(d._rgba)||[],q(e.props,function(a,b){if(null!=g[b.idx])return c=g[b.idx]===f[b.idx]}));return c});return c},_space:function(){var a=[],b=this;q(h,function(c,d){b[d.cache]&&a.push(c)});return a.pop()},transition:function(a,b){var d=l(a),e=d._space(),f=h[e],g=0===this.alpha()?l("transparent"):this,
k=g[f.cache]||f.to(g._rgba),n=k.slice(),d=d[f.cache];q(f.props,function(a,e){var f=e.idx,g=k[f],h=d[f],l=m[e.type]||{};null!==h&&(null===g?n[f]=h:(l.mod&&(h-g>l.mod/2?g+=l.mod:g-h>l.mod/2&&(g-=l.mod)),n[f]=c((h-g)*b+g,e)))});return this[e](n)},blend:function(a){if(1===this._rgba[3])return this;var c=this._rgba.slice(),d=c.pop(),e=l(a)._rgba;return l(b.map(c,function(a,b){return(1-d)*e[b]+d*a}))},toRgbaString:function(){var a="rgba(",c=b.map(this._rgba,function(a,b){return null==a?2<b?1:0:a});1===
c[3]&&(c.pop(),a="rgb(");return a+c.join()+")"},toHslaString:function(){var a="hsla(",c=b.map(this.hsla(),function(a,b){null==a&&(a=2<b?1:0);b&&3>b&&(a=Math.round(100*a)+"%");return a});1===c[3]&&(c.pop(),a="hsl(");return a+c.join()+")"},toHexString:function(a){var c=this._rgba.slice(),d=c.pop();a&&c.push(~~(255*d));return"#"+b.map(c,function(a){a=(a||0).toString(16);return 1===a.length?"0"+a:a}).join("")},toString:function(){return 0===this._rgba[3]?"transparent":this.toRgbaString()}});l.fn.parse.prototype=
l.fn;h.hsla.to=function(a){if(null==a[0]||null==a[1]||null==a[2])return[null,null,null,a[3]];var b=a[0]/255,c=a[1]/255,d=a[2]/255;a=a[3];var e=Math.max(b,c,d),f=Math.min(b,c,d),g=e-f,h=e+f,k=0.5*h,h=0===g?0:0.5>=k?g/h:g/(2-h);return[Math.round(f===e?0:b===e?60*(c-d)/g+360:c===e?60*(d-b)/g+120:60*(b-c)/g+240)%360,h,k,null==a?1:a]};h.hsla.from=function(a){if(null==a[0]||null==a[1]||null==a[2])return[null,null,null,a[3]];var b=a[0]/360,c=a[1],e=a[2];a=a[3];c=0.5>=e?e*(1+c):e+c-e*c;e=2*e-c;return[Math.round(255*
d(e,c,b+1/3)),Math.round(255*d(e,c,b)),Math.round(255*d(e,c,b-1/3)),a]};q(h,function(a,d){var e=d.props,h=d.cache,m=d.to,n=d.from;l.fn[a]=function(a){m&&!this[h]&&(this[h]=m(this._rgba));if(a===g)return this[h].slice();var d,k=b.type(a),s="array"===k||"object"===k?a:arguments,r=this[h].slice();q(e,function(a,b){var d=s["object"===k?a:b.idx];null==d&&(d=r[b.idx]);r[b.idx]=c(d,b)});return n?(d=l(n(r)),d[h]=r,d):l(r)};q(e,function(c,d){l.fn[c]||(l.fn[c]=function(e){var g=b.type(e),h="alpha"===c?this._hsla?
"hsla":"rgba":a,l=this[h](),m=l[d.idx];if("undefined"===g)return m;"function"===g&&(e=e.call(this,m),g=b.type(e));if(null==e&&d.empty)return this;"string"===g&&(g=k.exec(e))&&(e=m+parseFloat(g[2])*("+"===g[1]?1:-1));l[d.idx]=e;return this[h](l)})})});l.hook=function(c){c=c.split(" ");q(c,function(c,d){b.cssHooks[d]={set:function(c,e){var g,h="";if("transparent"!==e&&("string"!==b.type(e)||(g=a(e)))){e=l(g||e);if(!s.rgba&&1!==e._rgba[3]){for(g="backgroundColor"===d?c.parentNode:c;(""===h||"transparent"===
h)&&g&&g.style;)try{h=b.css(g,"backgroundColor"),g=g.parentNode}catch(k){}e=e.blend(h&&"transparent"!==h?h:"_default")}e=e.toRgbaString()}try{c.style[d]=e}catch(m){}}};b.fx.step[d]=function(a){a.colorInit||(a.start=l(a.elem,d),a.end=l(a.end),a.colorInit=!0);b.cssHooks[d].set(a.elem,a.start.transition(a.end,a.pos))}})};l.hook("backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor color columnRuleColor outlineColor textDecorationColor textEmphasisColor");b.cssHooks.borderColor=
{expand:function(a){var b={};q(["Top","Right","Bottom","Left"],function(c,d){b["border"+d+"Color"]=a});return b}};r=b.Color.names={aqua:"#00ffff",black:"#000000",blue:"#0000ff",fuchsia:"#ff00ff",gray:"#808080",green:"#008000",lime:"#00ff00",maroon:"#800000",navy:"#000080",olive:"#808000",purple:"#800080",red:"#ff0000",silver:"#c0c0c0",teal:"#008080",white:"#ffffff",yellow:"#ffff00",transparent:[null,null,null,0],_default:"#ffffff"}})(jQuery);(function(){function f(a){var c,f=a.ownerDocument.defaultView?
a.ownerDocument.defaultView.getComputedStyle(a,null):a.currentStyle,e={};if(f&&f.length&&f[0]&&f[f[0]])for(a=f.length;a--;)c=f[a],"string"===typeof f[c]&&(e[b.camelCase(c)]=f[c]);else for(c in f)"string"===typeof f[c]&&(e[c]=f[c]);return e}var g=["add","remove","toggle"],c={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};b.each(["borderLeftStyle","borderRightStyle","borderBottomStyle","borderTopStyle"],function(a,c){b.fx.step[c]=function(a){if("none"!==
a.end&&!a.setAttr||1===a.pos&&!a.setAttr)jQuery.style(a.elem,c,a.end),a.setAttr=!0}});b.fn.addBack||(b.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});b.effects.animateClass=function(a,d,k,e){var l=b.speed(d,k,e);return this.queue(function(){var d=b(this),e=d.attr("class")||"",k,n=l.children?d.find("*").addBack():d,n=n.map(function(){return{el:b(this),start:f(this)}});k=function(){b.each(g,function(b,c){if(a[c])d[c+"Class"](a[c])})};k();n=n.map(function(){this.end=
f(this.el[0]);var a=this.start,d=this.end,e={},g,h;for(g in d)h=d[g],a[g]===h||(c[g]||!b.fx.step[g]&&isNaN(parseFloat(h)))||(e[g]=h);this.diff=e;return this});d.attr("class",e);n=n.map(function(){var a=this,c=b.Deferred(),d=b.extend({},l,{queue:!1,complete:function(){c.resolve(a)}});this.el.animate(this.diff,d);return c.promise()});b.when.apply(b,n.get()).done(function(){k();b.each(arguments,function(){var a=this.el;b.each(this.diff,function(b){a.css(b,"")})});l.complete.call(d[0])})})};b.fn.extend({addClass:function(a){return function(c,
f,e,g){return f?b.effects.animateClass.call(this,{add:c},f,e,g):a.apply(this,arguments)}}(b.fn.addClass),removeClass:function(a){return function(c,f,e,g){return 1<arguments.length?b.effects.animateClass.call(this,{remove:c},f,e,g):a.apply(this,arguments)}}(b.fn.removeClass),toggleClass:function(a){return function(c,f,e,g,h){return"boolean"===typeof f||f===p?e?b.effects.animateClass.call(this,f?{add:c}:{remove:c},e,g,h):a.apply(this,arguments):b.effects.animateClass.call(this,{toggle:c},f,e,g)}}(b.fn.toggleClass),
switchClass:function(a,c,f,e,g){return b.effects.animateClass.call(this,{add:c,remove:a},f,e,g)}})})();(function(){function f(c,a,d,f){b.isPlainObject(c)&&(a=c,c=c.effect);c={effect:c};null==a&&(a={});b.isFunction(a)&&(f=a,d=null,a={});if("number"===typeof a||b.fx.speeds[a])f=d,d=a,a={};b.isFunction(d)&&(f=d,d=null);a&&b.extend(c,a);d=d||a.duration;c.duration=b.fx.off?0:"number"===typeof d?d:d in b.fx.speeds?b.fx.speeds[d]:b.fx.speeds._default;c.complete=f||a.complete;return c}function g(c){return!c||
("number"===typeof c||b.fx.speeds[c])||"string"===typeof c&&!b.effects.effect[c]||b.isFunction(c)||"object"===typeof c&&!c.effect?!0:!1}b.extend(b.effects,{version:"1.10.3",save:function(b,a){for(var d=0;d<a.length;d++)null!==a[d]&&b.data("ui-effects-"+a[d],b[0].style[a[d]])},restore:function(b,a){var d,f;for(f=0;f<a.length;f++)null!==a[f]&&(d=b.data("ui-effects-"+a[f]),d===p&&(d=""),b.css(a[f],d))},setMode:function(b,a){"toggle"===a&&(a=b.is(":hidden")?"show":"hide");return a},getBaseline:function(b,
a){var d,f;switch(b[0]){case "top":d=0;break;case "middle":d=0.5;break;case "bottom":d=1;break;default:d=b[0]/a.height}switch(b[1]){case "left":f=0;break;case "center":f=0.5;break;case "right":f=1;break;default:f=b[1]/a.width}return{x:f,y:d}},createWrapper:function(c){if(c.parent().is(".ui-effects-wrapper"))return c.parent();var a={width:c.outerWidth(!0),height:c.outerHeight(!0),"float":c.css("float")},d=b("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",
border:"none",margin:0,padding:0}),f={width:c.width(),height:c.height()},e=document.activeElement;try{e.id}catch(g){e=document.body}c.wrap(d);(c[0]===e||b.contains(c[0],e))&&b(e).focus();d=c.parent();"static"===c.css("position")?(d.css({position:"relative"}),c.css({position:"relative"})):(b.extend(a,{position:c.css("position"),zIndex:c.css("z-index")}),b.each(["top","left","bottom","right"],function(b,d){a[d]=c.css(d);isNaN(parseInt(a[d],10))&&(a[d]="auto")}),c.css({position:"relative",top:0,left:0,
right:"auto",bottom:"auto"}));c.css(f);return d.css(a).show()},removeWrapper:function(c){var a=document.activeElement;c.parent().is(".ui-effects-wrapper")&&(c.parent().replaceWith(c),(c[0]===a||b.contains(c[0],a))&&b(a).focus());return c},setTransition:function(c,a,d,f){f=f||{};b.each(a,function(a,b){var g=c.cssUnit(b);0<g[0]&&(f[b]=g[0]*d+g[1])});return f}});b.fn.extend({effect:function(){function c(c){function d(){b.isFunction(g)&&g.call(f[0]);b.isFunction(c)&&c()}var f=b(this),g=a.complete,k=a.mode;
(f.is(":hidden")?"hide"===k:"show"===k)?(f[k](),d()):e.call(f[0],a,d)}var a=f.apply(this,arguments),d=a.mode,g=a.queue,e=b.effects.effect[a.effect];return b.fx.off||!e?d?this[d](a.duration,a.complete):this.each(function(){a.complete&&a.complete.call(this)}):!1===g?this.each(c):this.queue(g||"fx",c)},show:function(b){return function(a){if(g(a))return b.apply(this,arguments);var d=f.apply(this,arguments);d.mode="show";return this.effect.call(this,d)}}(b.fn.show),hide:function(b){return function(a){if(g(a))return b.apply(this,
arguments);var d=f.apply(this,arguments);d.mode="hide";return this.effect.call(this,d)}}(b.fn.hide),toggle:function(b){return function(a){if(g(a)||"boolean"===typeof a)return b.apply(this,arguments);var d=f.apply(this,arguments);d.mode="toggle";return this.effect.call(this,d)}}(b.fn.toggle),cssUnit:function(c){var a=this.css(c),d=[];b.each(["em","px","%","pt"],function(b,c){0<a.indexOf(c)&&(d=[parseFloat(a),c])});return d}})})();(function(){var f={};b.each(["Quad","Cubic","Quart","Quint","Expo"],
function(b,c){f[c]=function(a){return Math.pow(a,b+2)}});b.extend(f,{Sine:function(b){return 1-Math.cos(b*Math.PI/2)},Circ:function(b){return 1-Math.sqrt(1-b*b)},Elastic:function(b){return 0===b||1===b?b:-Math.pow(2,8*(b-1))*Math.sin((80*(b-1)-7.5)*Math.PI/15)},Back:function(b){return b*b*(3*b-2)},Bounce:function(b){for(var c,a=4;b<((c=Math.pow(2,--a))-1)/11;);return 1/Math.pow(4,3-a)-7.5625*Math.pow((3*c-2)/22-b,2)}});b.each(f,function(f,c){b.easing["easeIn"+f]=c;b.easing["easeOut"+f]=function(a){return 1-
c(1-a)};b.easing["easeInOut"+f]=function(a){return 0.5>a?c(2*a)/2:1-c(-2*a+2)/2}})})()})(jQuery);(function(b,p){b.effects.effect.fade=function(f,g){var c=b(this),a=b.effects.setMode(c,f.mode||"toggle");c.animate({opacity:a},{queue:!1,duration:f.duration,easing:f.easing,complete:g})}})(jQuery);
(function(b,p){b.effects.effect.fold=function(f,g){var c=b(this),a="position top bottom left right height width".split(" "),d=b.effects.setMode(c,f.mode||"hide"),k="show"===d,e="hide"===d,d=f.size||15,l=/([0-9]+)%/.exec(d),h=!!f.horizFirst,m=k!==h,s=m?["width","height"]:["height","width"],n=f.duration/2,r,q={},p={};b.effects.save(c,a);c.show();r=b.effects.createWrapper(c).css({overflow:"hidden"});m=m?[r.width(),r.height()]:[r.height(),r.width()];l&&(d=parseInt(l[1],10)/100*m[e?0:1]);k&&r.css(h?{height:0,
width:d}:{height:d,width:0});q[s[0]]=k?m[0]:d;p[s[1]]=k?m[1]:0;r.animate(q,n,f.easing).animate(p,n,f.easing,function(){e&&c.hide();b.effects.restore(c,a);b.effects.removeWrapper(c);g()})}})(jQuery);
(function(b,p){b.effects.effect.puff=function(f,g){var c=b(this),a=b.effects.setMode(c,f.mode||"hide"),d="hide"===a,k=parseInt(f.percent,10)||150,e=k/100,l={height:c.height(),width:c.width(),outerHeight:c.outerHeight(),outerWidth:c.outerWidth()};b.extend(f,{effect:"scale",queue:!1,fade:!0,mode:a,complete:g,percent:d?k:100,from:d?l:{height:l.height*e,width:l.width*e,outerHeight:l.outerHeight*e,outerWidth:l.outerWidth*e}});c.effect(f)};b.effects.effect.scale=function(f,g){var c=b(this),a=b.extend(!0,
{},f),d=b.effects.setMode(c,f.mode||"effect"),k=parseInt(f.percent,10)||(0===parseInt(f.percent,10)?0:"hide"===d?0:100),e=f.direction||"both",l=f.origin,h={height:c.height(),width:c.width(),outerHeight:c.outerHeight(),outerWidth:c.outerWidth()},m="horizontal"!==e?k/100:1,k="vertical"!==e?k/100:1;a.effect="size";a.queue=!1;a.complete=g;"effect"!==d&&(a.origin=l||["middle","center"],a.restore=!0);a.from=f.from||("show"===d?{height:0,width:0,outerHeight:0,outerWidth:0}:h);a.to={height:h.height*m,width:h.width*
k,outerHeight:h.outerHeight*m,outerWidth:h.outerWidth*k};a.fade&&("show"===d&&(a.from.opacity=0,a.to.opacity=1),"hide"===d&&(a.from.opacity=1,a.to.opacity=0));c.effect(a)};b.effects.effect.size=function(f,g){var c,a,d,k,e,l,h=b(this),m="position top bottom left right width height overflow opacity".split(" ");e="position top bottom left right overflow opacity".split(" ");var s=["width","height","overflow"],n=["fontSize"],r=["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"],q=["borderLeftWidth",
"borderRightWidth","paddingLeft","paddingRight"],p=b.effects.setMode(h,f.mode||"effect"),w=f.restore||"effect"!==p,x=f.scale||"both";l=f.origin||["middle","center"];var t=h.css("position"),v=w?m:e,C={height:0,width:0,outerHeight:0,outerWidth:0};"show"===p&&h.show();e={height:h.height(),width:h.width(),outerHeight:h.outerHeight(),outerWidth:h.outerWidth()};"toggle"===f.mode&&"show"===p?(h.from=f.to||C,h.to=f.from||e):(h.from=f.from||("show"===p?C:e),h.to=f.to||("hide"===p?C:e));d=h.from.height/e.height;
k=h.from.width/e.width;c=h.to.height/e.height;a=h.to.width/e.width;if("box"===x||"both"===x)d!==c&&(v=v.concat(r),h.from=b.effects.setTransition(h,r,d,h.from),h.to=b.effects.setTransition(h,r,c,h.to)),k!==a&&(v=v.concat(q),h.from=b.effects.setTransition(h,q,k,h.from),h.to=b.effects.setTransition(h,q,a,h.to));"content"!==x&&"both"!==x||d===c||(v=v.concat(n).concat(s),h.from=b.effects.setTransition(h,n,d,h.from),h.to=b.effects.setTransition(h,n,c,h.to));b.effects.save(h,v);h.show();b.effects.createWrapper(h);
h.css("overflow","hidden").css(h.from);l&&(l=b.effects.getBaseline(l,e),h.from.top=(e.outerHeight-h.outerHeight())*l.y,h.from.left=(e.outerWidth-h.outerWidth())*l.x,h.to.top=(e.outerHeight-h.to.outerHeight)*l.y,h.to.left=(e.outerWidth-h.to.outerWidth)*l.x);h.css(h.from);if("content"===x||"both"===x)r=r.concat(["marginTop","marginBottom"]).concat(n),q=q.concat(["marginLeft","marginRight"]),s=m.concat(r).concat(q),h.find("*[width]").each(function(){var e=b(this),g=e.height(),h=e.width(),l=e.outerHeight(),
m=e.outerWidth();w&&b.effects.save(e,s);e.from={height:g*d,width:h*k,outerHeight:l*d,outerWidth:m*k};e.to={height:g*c,width:h*a,outerHeight:g*c,outerWidth:h*a};d!==c&&(e.from=b.effects.setTransition(e,r,d,e.from),e.to=b.effects.setTransition(e,r,c,e.to));k!==a&&(e.from=b.effects.setTransition(e,q,k,e.from),e.to=b.effects.setTransition(e,q,a,e.to));e.css(e.from);e.animate(e.to,f.duration,f.easing,function(){w&&b.effects.restore(e,s)})});h.animate(h.to,{queue:!1,duration:f.duration,easing:f.easing,
complete:function(){0===h.to.opacity&&h.css("opacity",h.from.opacity);"hide"===p&&h.hide();b.effects.restore(h,v);w||("static"===t?h.css({position:"relative",top:h.to.top,left:h.to.left}):b.each(["top","left"],function(a,b){h.css(b,function(b,c){var d=parseInt(c,10),e=a?h.to.left:h.to.top;return"auto"===c?e+"px":d+e+"px"})}));b.effects.removeWrapper(h);g()}})}})(jQuery);
(function(b,p){b.effects.effect.slide=function(f,g){var c=b(this),a="position top bottom left right width height".split(" "),d=b.effects.setMode(c,f.mode||"show"),k="show"===d,e=f.direction||"left",l="up"===e||"down"===e?"top":"left",e="up"===e||"left"===e,h,m={};b.effects.save(c,a);c.show();h=f.distance||c["top"===l?"outerHeight":"outerWidth"](!0);b.effects.createWrapper(c).css({overflow:"hidden"});k&&c.css(l,e?isNaN(h)?"-"+h:-h:h);m[l]=(k?e?"+=":"-=":e?"-=":"+=")+h;c.animate(m,{queue:!1,duration:f.duration,
easing:f.easing,complete:function(){"hide"===d&&c.hide();b.effects.restore(c,a);b.effects.removeWrapper(c);g()}})}})(jQuery);